// The file is autogenerated by ozconfgen.pl
// Do not edit this file as any changes will be overwritten

#define OZ_SKIN_DEFAULT 0
#define OZ_CSS_DEFAULT 1
#define OZ_LANG_DEFAULT 2
#define OZ_OPT_USE_AUTH 3
#define OZ_AUTH_TYPE 4
#define OZ_AUTH_RELAY 5
#define OZ_AUTH_HASH_SECRET 6
#define OZ_AUTH_HASH_IPS 7
#define OZ_AUTH_HASH_LOGINS 8
#define OZ_OPT_USE_API 9
#define OZ_OPT_USE_GOOG_RECAPTCHA 10
#define OZ_OPT_GOOG_RECAPTCHA_SITEKEY 11
#define OZ_OPT_GOOG_RECAPTCHA_SECRETKEY 12
#define OZ_DIR_EVENTS 13
#define OZ_USE_DEEP_STORAGE 14
#define OZ_DIR_IMAGES 15
#define OZ_DIR_SOUNDS 16
#define OZ_PATH_ZMS 17
#define OZ_COLOUR_JPEG_FILES 18
#define OZ_ADD_JPEG_COMMENTS 19
#define OZ_JPEG_FILE_QUALITY 20
#define OZ_JPEG_ALARM_FILE_QUALITY 21
#define OZ_JPEG_IMAGE_QUALITY 22
#define OZ_JPEG_STREAM_QUALITY 23
#define OZ_MPEG_TIMED_FRAMES 24
#define OZ_MPEG_LIVE_FORMAT 25
#define OZ_MPEG_REPLAY_FORMAT 26
#define OZ_RAND_STREAM 27
#define OZ_OPT_CAMBOZOLA 28
#define OZ_PATH_CAMBOZOLA 29
#define OZ_RELOAD_CAMBOZOLA 30
#define OZ_TIMESTAMP_ON_CAPTURE 31
#define OZ_CPU_EXTENSIONS 32
#define OZ_FAST_IMAGE_BLENDS 33
#define OZ_OPT_ADAPTIVE_SKIP 34
#define OZ_MAX_SUSPEND_TIME 35
#define OZ_OPT_REMOTE_CAMERAS 36
#define OZ_NETCAM_REGEXPS 37
#define OZ_HTTP_VERSION 38
#define OZ_HTTP_UA 39
#define OZ_HTTP_TIMEOUT 40
#define OZ_MIN_RTP_PORT 41
#define OZ_MAX_RTP_PORT 42
#define OZ_OPT_FFMPEG 43
#define OZ_PATH_FFMPEG 44
#define OZ_FFMPEG_INPUT_OPTIONS 45
#define OZ_FFMPEG_OUTPUT_OPTIONS 46
#define OZ_FFMPEG_FORMATS 47
#define OZ_FFMPEG_OPEN_TIMEOUT 48
#define OZ_LOG_LEVEL_SYSLOG 49
#define OZ_LOG_LEVEL_FILE 50
#define OZ_LOG_LEVEL_WEBLOG 51
#define OZ_LOG_LEVEL_DATABASE 52
#define OZ_LOG_DATABASE_LIMIT 53
#define OZ_LOG_DEBUG 54
#define OZ_LOG_DEBUG_TARGET 55
#define OZ_LOG_DEBUG_LEVEL 56
#define OZ_LOG_DEBUG_FILE 57
#define OZ_LOG_CHECK_PERIOD 58
#define OZ_LOG_ALERT_WAR_COUNT 59
#define OZ_LOG_ALERT_ERR_COUNT 60
#define OZ_LOG_ALERT_FAT_COUNT 61
#define OZ_LOG_ALARM_WAR_COUNT 62
#define OZ_LOG_ALARM_ERR_COUNT 63
#define OZ_LOG_ALARM_FAT_COUNT 64
#define OZ_RECORD_EVENT_STATS 65
#define OZ_RECORD_DIAG_IMAGES 66
#define OZ_DUMP_CORES 67
#define OZ_PATH_MAP 68
#define OZ_PATH_SOCKS 69
#define OZ_PATH_LOGS 70
#define OZ_PATH_SWAP 71
#define OZ_PATH_ARP 72
#define OZ_WEB_TITLE_PREFIX 73
#define OZ_WEB_RESIZE_CONSOLE 74
#define OZ_WEB_POPUP_ON_ALARM 75
#define OZ_OPT_X10 76
#define OZ_X10_DEVICE 77
#define OZ_X10_HOUSE_CODE 78
#define OZ_X10_DB_RELOAD_INTERVAL 79
#define OZ_WEB_SOUND_ON_ALARM 80
#define OZ_WEB_ALARM_SOUND 81
#define OZ_WEB_COMPACT_MONTAGE 82
#define OZ_OPT_FAST_DELETE 83
#define OZ_STRICT_VIDEO_CONFIG 84
#define OZ_SIGNAL_CHECK_POINTS 85
#define OZ_V4L_MULTI_BUFFER 86
#define OZ_CAPTURES_PER_FRAME 87
#define OZ_FILTER_RELOAD_DELAY 88
#define OZ_FILTER_EXECUTE_INTERVAL 89
#define OZ_OPT_UPLOAD 90
#define OZ_UPLOAD_ARCH_FORMAT 91
#define OZ_UPLOAD_ARCH_COMPRESS 92
#define OZ_UPLOAD_ARCH_ANALYSE 93
#define OZ_UPLOAD_PROTOCOL 94
#define OZ_UPLOAD_FTP_HOST 95
#define OZ_UPLOAD_HOST 96
#define OZ_UPLOAD_PORT 97
#define OZ_UPLOAD_FTP_USER 98
#define OZ_UPLOAD_USER 99
#define OZ_UPLOAD_FTP_PASS 100
#define OZ_UPLOAD_PASS 101
#define OZ_UPLOAD_FTP_LOC_DIR 102
#define OZ_UPLOAD_LOC_DIR 103
#define OZ_UPLOAD_FTP_REM_DIR 104
#define OZ_UPLOAD_REM_DIR 105
#define OZ_UPLOAD_FTP_TIMEOUT 106
#define OZ_UPLOAD_TIMEOUT 107
#define OZ_UPLOAD_STRICT 108
#define OZ_UPLOAD_FTP_PASSIVE 109
#define OZ_UPLOAD_FTP_DEBUG 110
#define OZ_UPLOAD_DEBUG 111
#define OZ_OPT_EMAIL 112
#define OZ_EMAIL_ADDRESS 113
#define OZ_EMAIL_TEXT 114
#define OZ_EMAIL_SUBJECT 115
#define OZ_EMAIL_BODY 116
#define OZ_OPT_MESSAGE 117
#define OZ_MESSAGE_ADDRESS 118
#define OZ_MESSAGE_TEXT 119
#define OZ_MESSAGE_SUBJECT 120
#define OZ_MESSAGE_BODY 121
#define OZ_NEW_MAIL_MODULES 122
#define OZ_EMAIL_HOST 123
#define OZ_FROM_EMAIL 124
#define OZ_URL 125
#define OZ_MAX_RESTART_DELAY 126
#define OZ_WATCH_CHECK_INTERVAL 127
#define OZ_WATCH_MAX_DELAY 128
#define OZ_RUN_AUDIT 129
#define OZ_AUDIT_CHECK_INTERVAL 130
#define OZ_AUDIT_MIN_AGE 131
#define OZ_FORCED_ALARM_SCORE 132
#define OZ_BULK_FRAME_INTERVAL 133
#define OZ_EVENT_CLOSE_MODE 134
#define OZ_FORCE_CLOSE_EVENTS 135
#define OZ_CREATE_ANALYSIS_IMAGES 136
#define OZ_WEIGHTED_ALARM_CENTRES 137
#define OZ_EVENT_IMAGE_DIGITS 138
#define OZ_DEFAULT_ASPECT_RATIO 139
#define OZ_USER_SELF_EDIT 140
#define OZ_OPT_FRAME_SERVER 141
#define OZ_FRAME_SOCKET_SIZE 142
#define OZ_OPT_CONTROL 143
#define OZ_OPT_TRIGGERS 144
#define OZ_CHECK_FOR_UPDATES 145
#define OZ_TELEMETRY_DATA 146
#define OZ_TELEMETRY_UUID 147
#define OZ_TELEMETRY_LAST_UPLOAD 148
#define OZ_UPDATE_CHECK_PROXY 149
#define OZ_SHM_KEY 150
#define OZ_WEB_REFRESH_METHOD 151
#define OZ_WEB_EVENT_SORT_FIELD 152
#define OZ_WEB_EVENT_SORT_ORDER 153
#define OZ_WEB_EVENTS_PER_PAGE 154
#define OZ_WEB_LIST_THUMBS 155
#define OZ_WEB_LIST_THUMB_WIDTH 156
#define OZ_WEB_LIST_THUMB_HEIGHT 157
#define OZ_WEB_USE_OBJECT_TAGS 158
#define OZ_WEB_H_REFRESH_MAIN 159
#define OZ_WEB_H_REFRESH_CYCLE 160
#define OZ_WEB_H_REFRESH_IMAGE 161
#define OZ_WEB_H_REFRESH_STATUS 162
#define OZ_WEB_H_REFRESH_EVENTS 163
#define OZ_WEB_H_CAN_STREAM 164
#define OZ_WEB_H_STREAM_METHOD 165
#define OZ_WEB_H_DEFAULT_SCALE 166
#define OZ_WEB_H_DEFAULT_RATE 167
#define OZ_WEB_H_VIDEO_BITRATE 168
#define OZ_WEB_H_VIDEO_MAXFPS 169
#define OZ_WEB_H_SCALE_THUMBS 170
#define OZ_WEB_H_EVENTS_VIEW 171
#define OZ_WEB_H_SHOW_PROGRESS 172
#define OZ_WEB_H_AJAX_TIMEOUT 173
#define OZ_WEB_M_REFRESH_MAIN 174
#define OZ_WEB_M_REFRESH_CYCLE 175
#define OZ_WEB_M_REFRESH_IMAGE 176
#define OZ_WEB_M_REFRESH_STATUS 177
#define OZ_WEB_M_REFRESH_EVENTS 178
#define OZ_WEB_M_CAN_STREAM 179
#define OZ_WEB_M_STREAM_METHOD 180
#define OZ_WEB_M_DEFAULT_SCALE 181
#define OZ_WEB_M_DEFAULT_RATE 182
#define OZ_WEB_M_VIDEO_BITRATE 183
#define OZ_WEB_M_VIDEO_MAXFPS 184
#define OZ_WEB_M_SCALE_THUMBS 185
#define OZ_WEB_M_EVENTS_VIEW 186
#define OZ_WEB_M_SHOW_PROGRESS 187
#define OZ_WEB_M_AJAX_TIMEOUT 188
#define OZ_WEB_L_REFRESH_MAIN 189
#define OZ_WEB_L_REFRESH_CYCLE 190
#define OZ_WEB_L_REFRESH_IMAGE 191
#define OZ_WEB_L_REFRESH_STATUS 192
#define OZ_WEB_L_REFRESH_EVENTS 193
#define OZ_WEB_L_CAN_STREAM 194
#define OZ_WEB_L_STREAM_METHOD 195
#define OZ_WEB_L_DEFAULT_SCALE 196
#define OZ_WEB_L_DEFAULT_RATE 197
#define OZ_WEB_L_VIDEO_BITRATE 198
#define OZ_WEB_L_VIDEO_MAXFPS 199
#define OZ_WEB_L_SCALE_THUMBS 200
#define OZ_WEB_L_EVENTS_VIEW 201
#define OZ_WEB_L_SHOW_PROGRESS 202
#define OZ_WEB_L_AJAX_TIMEOUT 203
#define OZ_WEB_P_CAN_STREAM 204
#define OZ_WEB_P_STREAM_METHOD 205
#define OZ_WEB_P_DEFAULT_SCALE 206
#define OZ_WEB_P_DEFAULT_RATE 207
#define OZ_WEB_P_VIDEO_BITRATE 208
#define OZ_WEB_P_VIDEO_MAXFPS 209
#define OZ_WEB_P_SCALE_THUMBS 210
#define OZ_WEB_P_AJAX_TIMEOUT 211
#define OZ_DYN_LAST_VERSION 212
#define OZ_DYN_CURR_VERSION 213
#define OZ_DYN_DB_VERSION 214
#define OZ_DYN_LAST_CHECK 215
#define OZ_DYN_NEXT_REMINDER 216
#define OZ_DYN_DONATE_REMINDER_TIME 217
#define OZ_DYN_SHOW_DONATE_REMINDER 218
#define OZ_EYEOZ_DEBUG 219
#define OZ_EYEOZ_LOG_TO_FILE 220
#define OZ_EYEOZ_LOG_FILE 221
#define OZ_EYEOZ_EVENT_VCODEC 222
#define OZ_EYEOZ_FEED_VCODEC 223
#define OZ_EYEOZ_H264_DEFAULT_BR 224
#define OZ_EYEOZ_H264_DEFAULT_EVBR 225
#define OZ_EYEOZ_H264_TIMEOUT 226
#define OZ_EYEOZ_SEG_DURATION 227


#define OZ_MAX_CFG_ID 227

#define OZ_CFG_DECLARE_LIST \
    const char *skin_default;\
    const char *css_default;\
    const char *lang_default;\
    bool opt_use_auth;\
    const char *auth_type;\
    const char *auth_relay;\
    const char *auth_hash_secret;\
    bool auth_hash_ips;\
    bool auth_hash_logins;\
    bool opt_use_api;\
    bool opt_use_goog_recaptcha;\
    const char *opt_goog_recaptcha_sitekey;\
    const char *opt_goog_recaptcha_secretkey;\
    const char *dir_events;\
    bool use_deep_storage;\
    const char *dir_images;\
    const char *dir_sounds;\
    const char *path_ozs;\
    bool colour_jpeg_files;\
    bool add_jpeg_comments;\
    int jpeg_file_quality;\
    int jpeg_alarm_file_quality;\
    int jpeg_image_quality;\
    int jpeg_stream_quality;\
    bool mpeg_timed_frames;\
    const char *mpeg_live_format;\
    const char *mpeg_replay_format;\
    bool rand_stream;\
    bool opt_cambozola;\
    const char *path_cambozola;\
    int reload_cambozola;\
    bool timestamp_on_capture;\
    bool cpu_extensions;\
    bool fast_image_blends;\
    bool opt_adaptive_skip;\
    int max_suspend_time;\
    bool opt_remote_cameras;\
    bool netcam_regexps;\
    const char *http_version;\
    const char *http_ua;\
    int http_timeout;\
    int min_rtp_port;\
    int max_rtp_port;\
    bool opt_ffmpeg;\
    const char *path_ffmpeg;\
    const char *ffmpeg_input_options;\
    const char *ffmpeg_output_options;\
    const char *ffmpeg_formats;\
    int ffmpeg_open_timeout;\
    int log_level_syslog;\
    int log_level_file;\
    int log_level_weblog;\
    int log_level_database;\
    const char *log_database_limit;\
    bool log_debug;\
    const char *log_debug_target;\
    int log_debug_level;\
    const char *log_debug_file;\
    int log_check_period;\
    int log_alert_war_count;\
    int log_alert_err_count;\
    int log_alert_fat_count;\
    int log_alarm_war_count;\
    int log_alarm_err_count;\
    int log_alarm_fat_count;\
    bool record_event_stats;\
    bool record_diag_images;\
    bool dump_cores;\
    const char *path_map;\
    const char *path_socks;\
    const char *path_logs;\
    const char *path_swap;\
    const char *path_arp;\
    const char *web_title_prefix;\
    bool web_resize_console;\
    bool web_popup_on_alarm;\
    bool opt_x10;\
    const char *x10_device;\
    const char *x10_house_code;\
    int x10_db_reload_interval;\
    bool web_sound_on_alarm;\
    const char *web_alarm_sound;\
    bool web_compact_montage;\
    bool opt_fast_delete;\
    bool strict_video_config;\
    int signal_check_points;\
    bool v4l_multi_buffer;\
    int captures_per_frame;\
    int filter_reload_delay;\
    int filter_execute_interval;\
    bool opt_upload;\
    const char *upload_arch_format;\
    bool upload_arch_compress;\
    bool upload_arch_analyse;\
    const char *upload_protocol;\
    const char *upload_ftp_host;\
    const char *upload_host;\
    int upload_port;\
    const char *upload_ftp_user;\
    const char *upload_user;\
    const char *upload_ftp_pass;\
    const char *upload_pass;\
    const char *upload_ftp_loc_dir;\
    const char *upload_loc_dir;\
    const char *upload_ftp_rem_dir;\
    const char *upload_rem_dir;\
    int upload_ftp_timeout;\
    int upload_timeout;\
    bool upload_strict;\
    bool upload_ftp_passive;\
    bool upload_ftp_debug;\
    bool upload_debug;\
    bool opt_email;\
    const char *email_address;\
    const char *email_text;\
    const char *email_subject;\
    const char *email_body;\
    bool opt_message;\
    const char *message_address;\
    const char *message_text;\
    const char *message_subject;\
    const char *message_body;\
    bool new_mail_modules;\
    const char *email_host;\
    const char *from_email;\
    const char *url;\
    int max_restart_delay;\
    int watch_check_interval;\
    double watch_max_delay;\
    bool run_audit;\
    int audit_check_interval;\
    int audit_min_age;\
    int forced_alarm_score;\
    int bulk_frame_interval;\
    const char *event_close_mode;\
    bool force_close_events;\
    bool create_analysis_images;\
    bool weighted_alarm_centres;\
    int event_image_digits;\
    const char *default_aspect_ratio;\
    bool user_self_edit;\
    bool opt_frame_server;\
    int frame_socket_size;\
    bool opt_control;\
    bool opt_triggers;\
    bool check_for_updates;\
    bool telemetry_data;\
    const char *telemetry_uuid;\
    int telemetry_last_upload;\
    const char *update_check_proxy;\
    int shm_key;\
    const char *web_refresh_method;\
    const char *web_event_sort_field;\
    const char *web_event_sort_order;\
    int web_events_per_page;\
    bool web_list_thumbs;\
    int web_list_thumb_width;\
    int web_list_thumb_height;\
    bool web_use_object_tags;\
    int web_h_refresh_main;\
    int web_h_refresh_cycle;\
    int web_h_refresh_image;\
    int web_h_refresh_status;\
    int web_h_refresh_events;\
    const char *web_h_can_stream;\
    const char *web_h_stream_method;\
    int web_h_default_scale;\
    int web_h_default_rate;\
    int web_h_video_bitrate;\
    int web_h_video_maxfps;\
    bool web_h_scale_thumbs;\
    const char *web_h_events_view;\
    bool web_h_show_progress;\
    int web_h_ajax_timeout;\
    int web_m_refresh_main;\
    int web_m_refresh_cycle;\
    int web_m_refresh_image;\
    int web_m_refresh_status;\
    int web_m_refresh_events;\
    const char *web_m_can_stream;\
    const char *web_m_stream_method;\
    int web_m_default_scale;\
    int web_m_default_rate;\
    int web_m_video_bitrate;\
    int web_m_video_maxfps;\
    bool web_m_scale_thumbs;\
    const char *web_m_events_view;\
    bool web_m_show_progress;\
    int web_m_ajax_timeout;\
    int web_l_refresh_main;\
    int web_l_refresh_cycle;\
    int web_l_refresh_image;\
    int web_l_refresh_status;\
    int web_l_refresh_events;\
    const char *web_l_can_stream;\
    const char *web_l_stream_method;\
    int web_l_default_scale;\
    int web_l_default_rate;\
    int web_l_video_bitrate;\
    int web_l_video_maxfps;\
    bool web_l_scale_thumbs;\
    const char *web_l_events_view;\
    bool web_l_show_progress;\
    int web_l_ajax_timeout;\
    const char *web_p_can_stream;\
    const char *web_p_stream_method;\
    int web_p_default_scale;\
    int web_p_default_rate;\
    int web_p_video_bitrate;\
    int web_p_video_maxfps;\
    bool web_p_scale_thumbs;\
    int web_p_ajax_timeout;\
    const char *dyn_last_version;\
    const char *dyn_curr_version;\
    const char *dyn_db_version;\
    int dyn_last_check;\
    const char *dyn_next_reminder;\
    int dyn_donate_reminder_time;\
    bool dyn_show_donate_reminder;\
    bool eyeoz_debug;\
    bool eyeoz_log_to_file;\
    const char *eyeoz_log_file;\
    const char *eyeoz_event_vcodec;\
    const char *eyeoz_feed_vcodec;\
    const char *eyeoz_h264_default_br;\
    const char *eyeoz_h264_default_evbr;\
    const char *eyeoz_h264_timeout;\
    const char *eyeoz_seg_duration;\


#define OZ_CFG_ASSIGN_LIST \
    skin_default = (const char *)config.Item( OZ_SKIN_DEFAULT );\
    css_default = (const char *)config.Item( OZ_CSS_DEFAULT );\
    lang_default = (const char *)config.Item( OZ_LANG_DEFAULT );\
    opt_use_auth = (bool)config.Item( OZ_OPT_USE_AUTH );\
    auth_type = (const char *)config.Item( OZ_AUTH_TYPE );\
    auth_relay = (const char *)config.Item( OZ_AUTH_RELAY );\
    auth_hash_secret = (const char *)config.Item( OZ_AUTH_HASH_SECRET );\
    auth_hash_ips = (bool)config.Item( OZ_AUTH_HASH_IPS );\
    auth_hash_logins = (bool)config.Item( OZ_AUTH_HASH_LOGINS );\
    opt_use_api = (bool)config.Item( OZ_OPT_USE_API );\
    opt_use_goog_recaptcha = (bool)config.Item( OZ_OPT_USE_GOOG_RECAPTCHA );\
    opt_goog_recaptcha_sitekey = (const char *)config.Item( OZ_OPT_GOOG_RECAPTCHA_SITEKEY );\
    opt_goog_recaptcha_secretkey = (const char *)config.Item( OZ_OPT_GOOG_RECAPTCHA_SECRETKEY );\
    dir_events = (const char *)config.Item( OZ_DIR_EVENTS );\
    use_deep_storage = (bool)config.Item( OZ_USE_DEEP_STORAGE );\
    dir_images = (const char *)config.Item( OZ_DIR_IMAGES );\
    dir_sounds = (const char *)config.Item( OZ_DIR_SOUNDS );\
    path_ozs = (const char *)config.Item( OZ_PATH_ZMS );\
    colour_jpeg_files = (bool)config.Item( OZ_COLOUR_JPEG_FILES );\
    add_jpeg_comments = (bool)config.Item( OZ_ADD_JPEG_COMMENTS );\
    jpeg_file_quality = (int)config.Item( OZ_JPEG_FILE_QUALITY );\
    jpeg_alarm_file_quality = (int)config.Item( OZ_JPEG_ALARM_FILE_QUALITY );\
    jpeg_image_quality = (int)config.Item( OZ_JPEG_IMAGE_QUALITY );\
    jpeg_stream_quality = (int)config.Item( OZ_JPEG_STREAM_QUALITY );\
    mpeg_timed_frames = (bool)config.Item( OZ_MPEG_TIMED_FRAMES );\
    mpeg_live_format = (const char *)config.Item( OZ_MPEG_LIVE_FORMAT );\
    mpeg_replay_format = (const char *)config.Item( OZ_MPEG_REPLAY_FORMAT );\
    rand_stream = (bool)config.Item( OZ_RAND_STREAM );\
    opt_cambozola = (bool)config.Item( OZ_OPT_CAMBOZOLA );\
    path_cambozola = (const char *)config.Item( OZ_PATH_CAMBOZOLA );\
    reload_cambozola = (int)config.Item( OZ_RELOAD_CAMBOZOLA );\
    timestamp_on_capture = (bool)config.Item( OZ_TIMESTAMP_ON_CAPTURE );\
    cpu_extensions = (bool)config.Item( OZ_CPU_EXTENSIONS );\
    fast_image_blends = (bool)config.Item( OZ_FAST_IMAGE_BLENDS );\
    opt_adaptive_skip = (bool)config.Item( OZ_OPT_ADAPTIVE_SKIP );\
    max_suspend_time = (int)config.Item( OZ_MAX_SUSPEND_TIME );\
    opt_remote_cameras = (bool)config.Item( OZ_OPT_REMOTE_CAMERAS );\
    netcam_regexps = (bool)config.Item( OZ_NETCAM_REGEXPS );\
    http_version = (const char *)config.Item( OZ_HTTP_VERSION );\
    http_ua = (const char *)config.Item( OZ_HTTP_UA );\
    http_timeout = (int)config.Item( OZ_HTTP_TIMEOUT );\
    min_rtp_port = (int)config.Item( OZ_MIN_RTP_PORT );\
    max_rtp_port = (int)config.Item( OZ_MAX_RTP_PORT );\
    opt_ffmpeg = (bool)config.Item( OZ_OPT_FFMPEG );\
    path_ffmpeg = (const char *)config.Item( OZ_PATH_FFMPEG );\
    ffmpeg_input_options = (const char *)config.Item( OZ_FFMPEG_INPUT_OPTIONS );\
    ffmpeg_output_options = (const char *)config.Item( OZ_FFMPEG_OUTPUT_OPTIONS );\
    ffmpeg_formats = (const char *)config.Item( OZ_FFMPEG_FORMATS );\
    ffmpeg_open_timeout = (int)config.Item( OZ_FFMPEG_OPEN_TIMEOUT );\
    log_level_syslog = (int)config.Item( OZ_LOG_LEVEL_SYSLOG );\
    log_level_file = (int)config.Item( OZ_LOG_LEVEL_FILE );\
    log_level_weblog = (int)config.Item( OZ_LOG_LEVEL_WEBLOG );\
    log_level_database = (int)config.Item( OZ_LOG_LEVEL_DATABASE );\
    log_database_limit = (const char *)config.Item( OZ_LOG_DATABASE_LIMIT );\
    log_debug = (bool)config.Item( OZ_LOG_DEBUG );\
    log_debug_target = (const char *)config.Item( OZ_LOG_DEBUG_TARGET );\
    log_debug_level = (int)config.Item( OZ_LOG_DEBUG_LEVEL );\
    log_debug_file = (const char *)config.Item( OZ_LOG_DEBUG_FILE );\
    log_check_period = (int)config.Item( OZ_LOG_CHECK_PERIOD );\
    log_alert_war_count = (int)config.Item( OZ_LOG_ALERT_WAR_COUNT );\
    log_alert_err_count = (int)config.Item( OZ_LOG_ALERT_ERR_COUNT );\
    log_alert_fat_count = (int)config.Item( OZ_LOG_ALERT_FAT_COUNT );\
    log_alarm_war_count = (int)config.Item( OZ_LOG_ALARM_WAR_COUNT );\
    log_alarm_err_count = (int)config.Item( OZ_LOG_ALARM_ERR_COUNT );\
    log_alarm_fat_count = (int)config.Item( OZ_LOG_ALARM_FAT_COUNT );\
    record_event_stats = (bool)config.Item( OZ_RECORD_EVENT_STATS );\
    record_diag_images = (bool)config.Item( OZ_RECORD_DIAG_IMAGES );\
    dump_cores = (bool)config.Item( OZ_DUMP_CORES );\
    path_map = (const char *)config.Item( OZ_PATH_MAP );\
    path_socks = (const char *)config.Item( OZ_PATH_SOCKS );\
    path_logs = (const char *)config.Item( OZ_PATH_LOGS );\
    path_swap = (const char *)config.Item( OZ_PATH_SWAP );\
    path_arp = (const char *)config.Item( OZ_PATH_ARP );\
    web_title_prefix = (const char *)config.Item( OZ_WEB_TITLE_PREFIX );\
    web_resize_console = (bool)config.Item( OZ_WEB_RESIZE_CONSOLE );\
    web_popup_on_alarm = (bool)config.Item( OZ_WEB_POPUP_ON_ALARM );\
    opt_x10 = (bool)config.Item( OZ_OPT_X10 );\
    x10_device = (const char *)config.Item( OZ_X10_DEVICE );\
    x10_house_code = (const char *)config.Item( OZ_X10_HOUSE_CODE );\
    x10_db_reload_interval = (int)config.Item( OZ_X10_DB_RELOAD_INTERVAL );\
    web_sound_on_alarm = (bool)config.Item( OZ_WEB_SOUND_ON_ALARM );\
    web_alarm_sound = (const char *)config.Item( OZ_WEB_ALARM_SOUND );\
    web_compact_montage = (bool)config.Item( OZ_WEB_COMPACT_MONTAGE );\
    opt_fast_delete = (bool)config.Item( OZ_OPT_FAST_DELETE );\
    strict_video_config = (bool)config.Item( OZ_STRICT_VIDEO_CONFIG );\
    signal_check_points = (int)config.Item( OZ_SIGNAL_CHECK_POINTS );\
    v4l_multi_buffer = (bool)config.Item( OZ_V4L_MULTI_BUFFER );\
    captures_per_frame = (int)config.Item( OZ_CAPTURES_PER_FRAME );\
    filter_reload_delay = (int)config.Item( OZ_FILTER_RELOAD_DELAY );\
    filter_execute_interval = (int)config.Item( OZ_FILTER_EXECUTE_INTERVAL );\
    opt_upload = (bool)config.Item( OZ_OPT_UPLOAD );\
    upload_arch_format = (const char *)config.Item( OZ_UPLOAD_ARCH_FORMAT );\
    upload_arch_compress = (bool)config.Item( OZ_UPLOAD_ARCH_COMPRESS );\
    upload_arch_analyse = (bool)config.Item( OZ_UPLOAD_ARCH_ANALYSE );\
    upload_protocol = (const char *)config.Item( OZ_UPLOAD_PROTOCOL );\
    upload_ftp_host = (const char *)config.Item( OZ_UPLOAD_FTP_HOST );\
    upload_host = (const char *)config.Item( OZ_UPLOAD_HOST );\
    upload_port = (int)config.Item( OZ_UPLOAD_PORT );\
    upload_ftp_user = (const char *)config.Item( OZ_UPLOAD_FTP_USER );\
    upload_user = (const char *)config.Item( OZ_UPLOAD_USER );\
    upload_ftp_pass = (const char *)config.Item( OZ_UPLOAD_FTP_PASS );\
    upload_pass = (const char *)config.Item( OZ_UPLOAD_PASS );\
    upload_ftp_loc_dir = (const char *)config.Item( OZ_UPLOAD_FTP_LOC_DIR );\
    upload_loc_dir = (const char *)config.Item( OZ_UPLOAD_LOC_DIR );\
    upload_ftp_rem_dir = (const char *)config.Item( OZ_UPLOAD_FTP_REM_DIR );\
    upload_rem_dir = (const char *)config.Item( OZ_UPLOAD_REM_DIR );\
    upload_ftp_timeout = (int)config.Item( OZ_UPLOAD_FTP_TIMEOUT );\
    upload_timeout = (int)config.Item( OZ_UPLOAD_TIMEOUT );\
    upload_strict = (bool)config.Item( OZ_UPLOAD_STRICT );\
    upload_ftp_passive = (bool)config.Item( OZ_UPLOAD_FTP_PASSIVE );\
    upload_ftp_debug = (bool)config.Item( OZ_UPLOAD_FTP_DEBUG );\
    upload_debug = (bool)config.Item( OZ_UPLOAD_DEBUG );\
    opt_email = (bool)config.Item( OZ_OPT_EMAIL );\
    email_address = (const char *)config.Item( OZ_EMAIL_ADDRESS );\
    email_text = (const char *)config.Item( OZ_EMAIL_TEXT );\
    email_subject = (const char *)config.Item( OZ_EMAIL_SUBJECT );\
    email_body = (const char *)config.Item( OZ_EMAIL_BODY );\
    opt_message = (bool)config.Item( OZ_OPT_MESSAGE );\
    message_address = (const char *)config.Item( OZ_MESSAGE_ADDRESS );\
    message_text = (const char *)config.Item( OZ_MESSAGE_TEXT );\
    message_subject = (const char *)config.Item( OZ_MESSAGE_SUBJECT );\
    message_body = (const char *)config.Item( OZ_MESSAGE_BODY );\
    new_mail_modules = (bool)config.Item( OZ_NEW_MAIL_MODULES );\
    email_host = (const char *)config.Item( OZ_EMAIL_HOST );\
    from_email = (const char *)config.Item( OZ_FROM_EMAIL );\
    url = (const char *)config.Item( OZ_URL );\
    max_restart_delay = (int)config.Item( OZ_MAX_RESTART_DELAY );\
    watch_check_interval = (int)config.Item( OZ_WATCH_CHECK_INTERVAL );\
    watch_max_delay = (double) config.Item( OZ_WATCH_MAX_DELAY );\
    run_audit = (bool)config.Item( OZ_RUN_AUDIT );\
    audit_check_interval = (int)config.Item( OZ_AUDIT_CHECK_INTERVAL );\
    audit_min_age = (int)config.Item( OZ_AUDIT_MIN_AGE );\
    forced_alarm_score = (int)config.Item( OZ_FORCED_ALARM_SCORE );\
    bulk_frame_interval = (int)config.Item( OZ_BULK_FRAME_INTERVAL );\
    event_close_mode = (const char *)config.Item( OZ_EVENT_CLOSE_MODE );\
    force_close_events = (bool)config.Item( OZ_FORCE_CLOSE_EVENTS );\
    create_analysis_images = (bool)config.Item( OZ_CREATE_ANALYSIS_IMAGES );\
    weighted_alarm_centres = (bool)config.Item( OZ_WEIGHTED_ALARM_CENTRES );\
    event_image_digits = (int)config.Item( OZ_EVENT_IMAGE_DIGITS );\
    default_aspect_ratio = (const char *)config.Item( OZ_DEFAULT_ASPECT_RATIO );\
    user_self_edit = (bool)config.Item( OZ_USER_SELF_EDIT );\
    opt_frame_server = (bool)config.Item( OZ_OPT_FRAME_SERVER );\
    frame_socket_size = (int)config.Item( OZ_FRAME_SOCKET_SIZE );\
    opt_control = (bool)config.Item( OZ_OPT_CONTROL );\
    opt_triggers = (bool)config.Item( OZ_OPT_TRIGGERS );\
    check_for_updates = (bool)config.Item( OZ_CHECK_FOR_UPDATES );\
    telemetry_data = (bool)config.Item( OZ_TELEMETRY_DATA );\
    telemetry_uuid = (const char *)config.Item( OZ_TELEMETRY_UUID );\
    telemetry_last_upload = (int)config.Item( OZ_TELEMETRY_LAST_UPLOAD );\
    update_check_proxy = (const char *)config.Item( OZ_UPDATE_CHECK_PROXY );\
    shm_key = (int)config.Item( OZ_SHM_KEY );\
    web_refresh_method = (const char *)config.Item( OZ_WEB_REFRESH_METHOD );\
    web_event_sort_field = (const char *)config.Item( OZ_WEB_EVENT_SORT_FIELD );\
    web_event_sort_order = (const char *)config.Item( OZ_WEB_EVENT_SORT_ORDER );\
    web_events_per_page = (int)config.Item( OZ_WEB_EVENTS_PER_PAGE );\
    web_list_thumbs = (bool)config.Item( OZ_WEB_LIST_THUMBS );\
    web_list_thumb_width = (int)config.Item( OZ_WEB_LIST_THUMB_WIDTH );\
    web_list_thumb_height = (int)config.Item( OZ_WEB_LIST_THUMB_HEIGHT );\
    web_use_object_tags = (bool)config.Item( OZ_WEB_USE_OBJECT_TAGS );\
    web_h_refresh_main = (int)config.Item( OZ_WEB_H_REFRESH_MAIN );\
    web_h_refresh_cycle = (int)config.Item( OZ_WEB_H_REFRESH_CYCLE );\
    web_h_refresh_image = (int)config.Item( OZ_WEB_H_REFRESH_IMAGE );\
    web_h_refresh_status = (int)config.Item( OZ_WEB_H_REFRESH_STATUS );\
    web_h_refresh_events = (int)config.Item( OZ_WEB_H_REFRESH_EVENTS );\
    web_h_can_stream = (const char *)config.Item( OZ_WEB_H_CAN_STREAM );\
    web_h_stream_method = (const char *)config.Item( OZ_WEB_H_STREAM_METHOD );\
    web_h_default_scale = (int)config.Item( OZ_WEB_H_DEFAULT_SCALE );\
    web_h_default_rate = (int)config.Item( OZ_WEB_H_DEFAULT_RATE );\
    web_h_video_bitrate = (int)config.Item( OZ_WEB_H_VIDEO_BITRATE );\
    web_h_video_maxfps = (int)config.Item( OZ_WEB_H_VIDEO_MAXFPS );\
    web_h_scale_thumbs = (bool)config.Item( OZ_WEB_H_SCALE_THUMBS );\
    web_h_events_view = (const char *)config.Item( OZ_WEB_H_EVENTS_VIEW );\
    web_h_show_progress = (bool)config.Item( OZ_WEB_H_SHOW_PROGRESS );\
    web_h_ajax_timeout = (int)config.Item( OZ_WEB_H_AJAX_TIMEOUT );\
    web_m_refresh_main = (int)config.Item( OZ_WEB_M_REFRESH_MAIN );\
    web_m_refresh_cycle = (int)config.Item( OZ_WEB_M_REFRESH_CYCLE );\
    web_m_refresh_image = (int)config.Item( OZ_WEB_M_REFRESH_IMAGE );\
    web_m_refresh_status = (int)config.Item( OZ_WEB_M_REFRESH_STATUS );\
    web_m_refresh_events = (int)config.Item( OZ_WEB_M_REFRESH_EVENTS );\
    web_m_can_stream = (const char *)config.Item( OZ_WEB_M_CAN_STREAM );\
    web_m_stream_method = (const char *)config.Item( OZ_WEB_M_STREAM_METHOD );\
    web_m_default_scale = (int)config.Item( OZ_WEB_M_DEFAULT_SCALE );\
    web_m_default_rate = (int)config.Item( OZ_WEB_M_DEFAULT_RATE );\
    web_m_video_bitrate = (int)config.Item( OZ_WEB_M_VIDEO_BITRATE );\
    web_m_video_maxfps = (int)config.Item( OZ_WEB_M_VIDEO_MAXFPS );\
    web_m_scale_thumbs = (bool)config.Item( OZ_WEB_M_SCALE_THUMBS );\
    web_m_events_view = (const char *)config.Item( OZ_WEB_M_EVENTS_VIEW );\
    web_m_show_progress = (bool)config.Item( OZ_WEB_M_SHOW_PROGRESS );\
    web_m_ajax_timeout = (int)config.Item( OZ_WEB_M_AJAX_TIMEOUT );\
    web_l_refresh_main = (int)config.Item( OZ_WEB_L_REFRESH_MAIN );\
    web_l_refresh_cycle = (int)config.Item( OZ_WEB_L_REFRESH_CYCLE );\
    web_l_refresh_image = (int)config.Item( OZ_WEB_L_REFRESH_IMAGE );\
    web_l_refresh_status = (int)config.Item( OZ_WEB_L_REFRESH_STATUS );\
    web_l_refresh_events = (int)config.Item( OZ_WEB_L_REFRESH_EVENTS );\
    web_l_can_stream = (const char *)config.Item( OZ_WEB_L_CAN_STREAM );\
    web_l_stream_method = (const char *)config.Item( OZ_WEB_L_STREAM_METHOD );\
    web_l_default_scale = (int)config.Item( OZ_WEB_L_DEFAULT_SCALE );\
    web_l_default_rate = (int)config.Item( OZ_WEB_L_DEFAULT_RATE );\
    web_l_video_bitrate = (int)config.Item( OZ_WEB_L_VIDEO_BITRATE );\
    web_l_video_maxfps = (int)config.Item( OZ_WEB_L_VIDEO_MAXFPS );\
    web_l_scale_thumbs = (bool)config.Item( OZ_WEB_L_SCALE_THUMBS );\
    web_l_events_view = (const char *)config.Item( OZ_WEB_L_EVENTS_VIEW );\
    web_l_show_progress = (bool)config.Item( OZ_WEB_L_SHOW_PROGRESS );\
    web_l_ajax_timeout = (int)config.Item( OZ_WEB_L_AJAX_TIMEOUT );\
    web_p_can_stream = (const char *)config.Item( OZ_WEB_P_CAN_STREAM );\
    web_p_stream_method = (const char *)config.Item( OZ_WEB_P_STREAM_METHOD );\
    web_p_default_scale = (int)config.Item( OZ_WEB_P_DEFAULT_SCALE );\
    web_p_default_rate = (int)config.Item( OZ_WEB_P_DEFAULT_RATE );\
    web_p_video_bitrate = (int)config.Item( OZ_WEB_P_VIDEO_BITRATE );\
    web_p_video_maxfps = (int)config.Item( OZ_WEB_P_VIDEO_MAXFPS );\
    web_p_scale_thumbs = (bool)config.Item( OZ_WEB_P_SCALE_THUMBS );\
    web_p_ajax_timeout = (int)config.Item( OZ_WEB_P_AJAX_TIMEOUT );\
    dyn_last_version = (const char *)config.Item( OZ_DYN_LAST_VERSION );\
    dyn_curr_version = (const char *)config.Item( OZ_DYN_CURR_VERSION );\
    dyn_db_version = (const char *)config.Item( OZ_DYN_DB_VERSION );\
    dyn_last_check = (int)config.Item( OZ_DYN_LAST_CHECK );\
    dyn_next_reminder = (const char *)config.Item( OZ_DYN_NEXT_REMINDER );\
    dyn_donate_reminder_time = (int)config.Item( OZ_DYN_DONATE_REMINDER_TIME );\
    dyn_show_donate_reminder = (bool)config.Item( OZ_DYN_SHOW_DONATE_REMINDER );\
    eyeoz_debug = (bool)config.Item( OZ_EYEOZ_DEBUG );\
    eyeoz_log_to_file = (bool)config.Item( OZ_EYEOZ_LOG_TO_FILE );\
    eyeoz_log_file = (const char *)config.Item( OZ_EYEOZ_LOG_FILE );\
    eyeoz_event_vcodec = (const char *)config.Item( OZ_EYEOZ_EVENT_VCODEC );\
    eyeoz_feed_vcodec = (const char *)config.Item( OZ_EYEOZ_FEED_VCODEC );\
    eyeoz_h264_default_br = (const char *)config.Item( OZ_EYEOZ_H264_DEFAULT_BR );\
    eyeoz_h264_default_evbr = (const char *)config.Item( OZ_EYEOZ_H264_DEFAULT_EVBR );\
    eyeoz_h264_timeout = (const char *)config.Item( OZ_EYEOZ_H264_TIMEOUT );\
    eyeoz_seg_duration = (const char *)config.Item( OZ_EYEOZ_SEG_DURATION );\


